#Tue Oct 14 16:31:55 CEST 2025
GROUP=dev.iurysouza
IMPLEMENTATION_CLASS=dev.iurysouza.modulegraph.gradle.ModuleGraphPlugin
IMPLEMENTATION_CLASS_SETTINGS=dev.iurysouza.modulegraph.gradle.ModuleGraphSettingsPlugin
DESCRIPTION=Generates and embbed a mermaid graph showing the project's modules relationships in your README.md file.
VERSION=0.13.0
ID=dev.iurysouza.modulegraph
VCS_URL=https\://github.com/iurysza/module-graph
DISPLAY_NAME=Module Graph Generator
WEBSITE=https\://github.com/iurysza/module-graph
