name: Validate Gradle Wrapper
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

