name: Publish Plugin to Portal

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue

      - name: Publish on Plugin Portal
        if: success()
        run: ./gradlew --project-dir plugin-build setupPluginUploadFromEnvironment publishPlugins
